### ISSUE TITLE
About cam_pts_to_angle

### ISSUE THREAD

**Issue by hongxiaoy** [astra-vision/SceneRF#18]
https://github.com/astra-vision/SceneRF/blob/f55d944f7df49213332467e81e3b245301a40870/scenerf/models/spherical_mapping.py#L100C47-L100C47

你好，在看代码的时候这里的 X，Y 轴的方向定义我不太理解，因为相机坐标系下的 X 是向右的，Y 是向下的，Z 是垂直相机光心向外的，就像 KITTI 数据集中关于坐标系展示的那样。所以这里的关于 -Y 轴 以及 关于 X 轴角度的计算我不太理解。可以帮我看看吗，非常感谢！

![image](https://github.com/astra-vision/SceneRF/assets/112234465/61d6579d-41cb-4409-8896-0e801bec7b39)

**Comment by anhquancao** [comment]
Hi,
I don't use the coordinates in KITTI. I follow this to compute (cartesian to spherical)
https://math.libretexts.org/Bookshelves/Calculus/Calculus_(OpenStax)/12%3A_Vectors_in_Space/12.07%3A_Cylindrical_and_Spherical_Coordinates

**Comment by hongxiaoy** [comment]
> Hi, I don't use the coordinates in KITTI. I follow this to compute (cartesian to spherical) https://math.libretexts.org/Bookshelves/Calculus/Calculus_(OpenStax)/12%3A_Vectors_in_Space/12.07%3A_Cylindrical_and_Spherical_Coordinates

Sorry, I still cannot grab the cam_pts_2_angle function, even though I know the sphere coordinate, I didn't get what the comment in code "wrt minus y direction" and "wrt to x direction"  means. I tried to draw a pic to lead my thought but failed, may you help me more. Thanks a lot!
![cam_pts_2_angle](https://github.com/astra-vision/SceneRF/assets/112234465/eebd261a-e0e9-46a4-b1c8-70bac7741d61)

**Comment by anhquancao** [comment]
For a ray through a pixel, The vertical angle is the angle of the ray with the -Oy axis (you can see I have [-y here](https://github.com/astra-vision/SceneRF/blob/main/scenerf/models/spherical_mapping.py#L100)) of the camera coordinate. For example, if -Oy axis is the z axis in the picture then the vertical angle is $\varphi$
![image](https://github.com/astra-vision/SceneRF/assets/9668858/0373b7a2-1551-4c41-9fd9-c4e794a5b8b9)

Similarly, the horizontal angle is w.r.t. to -Ox direction (even [x without minus](https://github.com/astra-vision/SceneRF/blob/main/scenerf/models/spherical_mapping.py#L101)) since I have "180 -" before. I remember I need to add "180-" to make the image flip correctly in the horizontal direction (Probably because the camera rotates down in KITTI). 

However, since I compute the angle for all pixels and normalize [by the max and min angle](https://github.com/astra-vision/SceneRF/blob/main/scenerf/models/spherical_mapping.py#L108), the direction of -Ox and -Oy are not important .

I use these formulas
![image](https://github.com/astra-vision/SceneRF/assets/9668858/3277bdb1-ed8b-4fda-91d3-48cd17fd8548)

**Comment by hongxiaoy** [comment]
Thanks  a lot! I got it! I was lost in some details before.
