### ISSUE TITLE
Some questions about performance against baseline Adabins

### ISSUE THREAD

**Issue by haiphamcse** [astra-vision/SceneRF#23]
Hi there, love your team's work! I just have a small question about the project.
In your paper, specifically table 6, the 2 depth-estimation baseline (AdaBins with LiDAR sup and Monodepth2 with self-sup) seems to have reasonable performance in voxel reconstruction compared to your method. Can you explain more why SceneRF (or other methods such as PixelNeRF) should be investigated, and why we don't just use SOTA depth-estimation method and unproject  + voxelized them and call it a day?
![image](https://github.com/astra-vision/SceneRF/assets/76871780/cfa708cc-422c-40d5-b261-e05bf65d58ab)

**Comment by anhquancao** [comment]
Hello @haiphamcse, thanks for your insightful question, and please correct me if I am wrong.

One point worth noting about scenerf/pixelnerf is that they learn a 3D scene representation, and this can be further enhanced by incorporating additional frames, as seen in scenerf, or by utilizing various setups like the one demonstrated in https://github.com/Brummi/BehindTheScenes, which employs fisheye and stereo cameras. In contrast, depth estimation methods primarily focus on learning the visible surface rather than a full 3D scene representation. This is why they are often referred to as 2.5D rather than true 3D representations.

**Comment by haiphamcse** [comment]
Thank you for your reply, it is very clear on your motivation! Best wishes on your next project, I will close the issue now.
