### ISSUE TITLE
Question about FPS in inference

### ISSUE THREAD

**Issue by haiphamcse** [astra-vision/SceneRF#24]
Hi there again. I want to ask a bit about the inference speed of the model in scene reconstruction (image to voxels). Have your team measured this? Currently in the codebase i'm seeing 3 different stages for inferencing (image2noveldepth, noveldepth2tsdf, tsdf2voxel), I am very curious about this. Hope to hear from you soon.

**Comment by anhquancao** [comment]
Hello @haiphamcse, I haven't calculated the frames per second (FPS) yet, but the inference time is primarily influenced by the number of views you'd like to generate. Each view typically requires about 2 seconds for generation. Additionally, the tsdf fusion process also scales linearly with the number of views.

However, the inference time can be significantly reduced by directly extracting the occupancy from the density volume, similar to the approach demonstrated in BTS paper: https://fwmb.github.io/bts/

**Comment by haiphamcse** [comment]
Hi there, thank you for your reply. Have the team done any test on the way to extract the occupancy out other than the TSDF fusion of novel views yet? To my best knowledge, to obtain the results in the paper 13.84 IoU we need to generate a lot of novel depth (~27 frames), it is necessary or a smaller amount of frames will still give comparable results

**Comment by anhquancao** [comment]
Hello @haiphamcse, I haven't experimented with obtaining the occupancy directly from the density field. In the case of SemKITTI, rotating views (angle != 0) only yielded marginal improvements, likely because the dataset mostly consists of front-facing images. I remembered sampling only 10 views with an angle of 0 and an interval of 1 meter also give roughly the same performance."

**Comment by haiphamcse** [comment]
Thank you for your reply. I will close the issue now.
